### ISSUE TITLE
[Feature]: Require multiple signers to approve a chainstate for there to be a reorg in Emily.

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-sbtc/sbtc#1003]
# Feature - Require multiple signers to approve a chainstate for there to be a reorg in Emily.

## 1. Description

The Emily API is made to be very simple, and in effect just a database so it currently trusts that new chainstates sent from signers are accurate. This ticket is to require multiple signers to approve a chainstate for it to initiate a reorg around it.

### 2.1 Acceptance Criteria:
   - [ ] Multiple signers need to approve a chainstate for it to be reorged around.
   - [ ] PR is created and merged with tests.

**Comment by aldur** [comment]
The sidecar now takes care of this.
