### ISSUE TITLE
[Feature]: The bridge should log deposit requests to Emily

### ISSUE THREAD

**Issue by aldur** [stacks-sbtc/sbtc#1137]
## 1. Description

We have seen a bug for which the bridge fails to issue a request to Emily _after_ a wallet transaction has been signed.
That's unfortunate and will lead to havoc, since those deposits will never be processed by the signers.

This issue won't fix that issue, but will allow us to remediate it, i.e. by having someone (e.g. L1 support) manually issuing another request to Emily with the proper parameters. 

## 2. Technical Details:

The bridge logs in a structured way (e.g., JSON) all required parameters to repeat an sBTC deposit notification to Emily in case it is required.

Logs should be both client and server side.

As a support user, I need to be able to take that structured logs and use it to manually re-issue a call to Emily if I need to.

**Comment by hozzjss** [comment]
resolved in https://github.com/stacks-network/sbtc-bridge/pull/63
